# Generated by Django 4.1.3 on 2023-02-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=200)),
                ('text', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='fbposts',
        ),
        migrations.DeleteModel(
            name='scehdule',
        ),
    ]
