# Generated by Django 4.1.3 on 2023-02-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_postmodel_every_postmodel_group_postmodel_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='every',
            field=models.CharField(choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('T', 'Thursday'), ('F', 'Friday'), ('S', 'Saturday'), ('S', 'Sunday')], default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='images/'),
        ),
    ]
