# Generated by Django 4.1.3 on 2023-02-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_postmodel_every_alter_postmodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(default=None, max_length=100)),
                ('username', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='postmodel',
            name='username',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
