# Generated by Django 4.1.3 on 2023-02-22 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_postmodel_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='username',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
