# Generated by Django 4.1.3 on 2023-02-23 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_postmodel_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='status',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
