# Generated by Django 4.1.3 on 2023-02-23 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_postmodel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FBAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default=None, max_length=100)),
                ('password', models.CharField(default=None, max_length=100)),
                ('username', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
