# Generated by Django 4.1.3 on 2023-02-23 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_fbaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbaccount',
            name='status',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
