# Generated by Django 4.1.3 on 2023-02-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_alter_postmodel_post_as'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='post_as',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
